# fly.toml app configuration file generated for dropcloud on 2024-11-20T00:22:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dropcloud'
primary_region = 'lhr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME = 'Dropcloud'
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  MAIL_MAILER = 'smtp'
  MAIL_HOST = 'smtp.mailgun.org'
  MAIL_PORT = '587'
  MAIL_ENCRYPTION = 'tls'
  MAIL_FROM_ADDRESS = 'hello@dropcloud.com'
  MAIL_FROM_NAME = 'Dropcloud'	

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
