name: Deploy to Fly.io

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    concurrency: deploy-group

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Fly.io CLI
      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      # Deploy the app
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Run migrations
      - name: Run migrations
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl ssh console --command "php artisan migrate --force"